<a href="https://colab.research.google.com/github/khuranakhurana430-alt/RNN-/blob/main/ML_for_Email_Spam_Detection_NLP_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
!mkdir -p ~/.kaggle
!cp KAGGLE.json ~/.kaggle/
!chmod 600 ~/.kaggle/KAGGLE.json

In [79]:
#PANDAS
import pandas as pd

#NLTK
import nltk
import re # regex expression (to remove the speacial characters from the data)
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('punkt_tab', force=True)
from nltk.corpus import stopwords # stop word library
from nltk.tokenize import word_tokenize # for tokenizing
from nltk.stem import PorterStemmer,WordNetLemmatizer # for stemming or lemmatization

#SKLEARN
from sklearn.preprocessing import LabelEncoder # to encode the y axis
from sklearn.model_selection import train_test_split  # to split and train
from sklearn.metrics import accuracy_score,classification_report  # scores
from sklearn.ensemble import AdaBoostClassifier # model
from sklearn.tree import DecisionTreeClassifier # weak learner
from sklearn.feature_extraction.text import CountVectorizer # bag of words model

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [30]:
from google.colab import files
files.upload()  # choose kaggle.json

Saving spam.csv to spam (1).csv

{'spam (1).csv': b'Category,Message\nham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."\nham,Ok lar... Joking wif u oni...\nspam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C\'s apply 08452810075over18\'s\nham,U dun say so early hor... U c already then say...\nham,"Nah I don\'t think he goes to usf, he lives around here though"\nspam,"FreeMsg Hey there darling it\'s been 3 week\'s now and no word back! I\'d like some fun you up for it still? Tb ok! XxX std chgs to send, \xc2\xa31.50 to rcv"\nham,Even my brother is not like to speak with me. They treat me like aids patent.\nham,As per your request \'Melle Melle (Oru Minnaminunginte Nurungu Vettam)\' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune\nspam,WINNER!! As a valued network customer you have been selected to receivea \xc2\xa3900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.\nspam,Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030\nham,"I\'m gonna be home soon and i don\'t want to talk about this stuff anymore tonight, k? I\'ve cried enough today."\nspam,"SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info"\nspam,"URGENT! You have won a 1 week FREE membership in our \xc2\xa3100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net LCCLTD POBOX 4403LDNW1A7RW18"\nham,I\'ve been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times.\nham,I HAVE A DATE ON SUNDAY WITH WILL!!\nspam,"XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL"\nham,Oh k...i\'m watching here:)\nham,Eh u remember how 2 spell his name... Yes i did. He v naughty make until i v wet.\nham,Fine if that\xc2\x92s the way u feel. That\xc2\x92s the way its gota b\nspam,"England v Macedonia - dont miss the goals/team news. Txt ur national team to 87077 eg ENGLAND to 87077 Try:WALES, SCOTLAND 4txt/\xc3\xba1.20 POBOXox36504W45WQ 16+"\nham,Is that seriously how you spell his name?\nham,I\xe2\x80\x98m going to try for 2 months ha ha only joking\nham,So \xc3\xbc pay first lar... Then when is da stock comin...\nham,Aft i finish my lunch then i go str down lor. Ard 3 smth lor. U finish ur lunch already?\nham,Ffffffffff. Alright no way I can meet up with you sooner?\nham,Just forced myself to eat a slice. I\'m really not hungry tho. This sucks. Mark is getting worried. He knows I\'m sick when I turn down pizza. Lol\nham,Lol your always so convincing.\nham,Did you catch the bus ? Are you frying an egg ? Did you make a tea? Are you eating your mom\'s left over dinner ? Do you feel my Love ?\nham,"I\'m back &amp; we\'re packing the car now, I\'ll let you know if there\'s room"\nham,Ahhh. Work. I vaguely remember that! What does it feel like? Lol\nham,"Wait that\'s still not all that clear, were you not sure about me being sarcastic or that that\'s why x doesn\'t want to live with us"\nham,Yeah he got in at 2 and was v apologetic. n had fallen out and she was actin like spoilt child and he got caught up in that. Till 2! But we won\'t go there! Not doing too badly cheers. You?\nham,K tell me anything about you.\nham,For fear of fainting with the of all that housework you just did? Quick have a cuppa\nspam,Thanks for your subscription to Ringtone UK your mobile will be charged \xc2\xa35/month Please confirm by replying YES or NO. If you reply NO you will not be charged\nham,Yup... Ok i go home look at the timings then i msg \xc3\xbc again... Xuhui going to learn on 2nd may too but her lesson is at 8am\nham,"Oops, I\'ll let you know when my roommate\'s done"\nham,I see the letter B on my car\nham,Anything lor... U decide...\nham,Hello! How\'s you and how did saturday go? I was just texting to see if you\'d decided to do anything tomo. Not that i\'m trying to invite myself or anything!\nham,Pls go ahead with watts. I just wanted to be sure. Do have a great weekend. Abiola\nham,"Did I forget to tell you ? I want you , I need you, I crave you ... But most of all ... I love you my sweet Arabian steed ... Mmmmmm ... Yummy"\nspam,07732584351 - Rodger Burns - MSG = We tried to call you re your reply to our sms for a free nokia mobile + free camcorder. Please call now 08000930705 for delivery tomorrow\nham,WHO ARE YOU SEEING?\nham,Great! I hope you like your man well endowed. I am  &lt;#&gt;  inches...\nham,No calls..messages..missed calls\nham,Didn\'t you get hep b immunisation in nigeria.\nham,"Fair enough, anything going on?"\nham,"Yeah hopefully, if tyler can\'t do it I could maybe ask around a bit"\nham,U don\'t know how stubborn I am. I didn\'t even want to go to the hospital. I kept telling Mark I\'m not a weak sucker. Hospitals are for weak suckers.\nham,What you thinked about me. First time you saw me in class.\nham,"A gram usually runs like  &lt;#&gt; , a half eighth is smarter though and gets you almost a whole second gram for  &lt;#&gt;"\nham,K fyi x has a ride early tomorrow morning but he\'s crashing at our place tonight\nham,"Wow. I never realized that you were so embarassed by your accomodations. I thought you liked it, since i was doing the best i could and you always seemed so happy about ""the cave"". I\'m sorry I didn\'t and don\'t have more to give. I\'m sorry i offered. I\'m sorry your room was so embarassing."\nspam,SMS. ac Sptv: The New Jersey Devils and the Detroit Red Wings play Ice Hockey. Correct or Incorrect? End? Reply END SPTV\nham,Do you know what Mallika Sherawat did yesterday? Find out now @  &lt;URL&gt;\nspam,"Congrats! 1 year special cinema pass for 2 is yours. call 09061209465 now! C Suprman V, Matrix3, StarWars3, etc all 4 FREE! bx420-ip4-5we. 150pm. Dont miss out!"\nham,"Sorry, I\'ll call later in meeting."\nham,Tell where you reached\nham,Yes..gauti and sehwag out of odi series.\nham,Your gonna have to pick up a $1 burger for yourself on your way home. I can\'t even move. Pain is killing me.\nham,Ha ha ha good joke. Girls are situation seekers.\nham,Its a part of checking IQ\nham,"Sorry my roommates took forever, it ok if I come by now?"\nham,Ok lar i double check wif da hair dresser already he said wun cut v short. He said will cut until i look nice.\nspam,"As a valued customer, I am pleased to advise you that following recent review of your Mob No. you are awarded with a \xc2\xa31500 Bonus Prize, call 09066364589"\nham,"Today is ""song dedicated day.."" Which song will u dedicate for me? Send this to all ur valuable frnds but first rply me..."\nspam,"Urgent UR awarded a complimentary trip to EuroDisinc Trav, Aco&Entry41 Or \xc2\xa31000. To claim txt DIS to 87121 18+6*\xc2\xa31.50(moreFrmMob. ShrAcomOrSglSuplt)10, LS1 3AJ"\nspam,"Did you hear about the new ""Divorce Barbie""? It comes with all of Ken\'s stuff!"\nham,I plane to give on this month end.\nham,Wah lucky man... Then can save money... Hee...\nham,Finished class where are you.\nham,HI BABE IM AT HOME NOW WANNA DO SOMETHING? XX\nham,K..k:)where are you?how did you performed?\nham,U can call me now...\nham,I am waiting machan. Call me once you free.\nham,Thats cool. i am a gentleman and will treat you with dignity and respect.\nham,I like you peoples very much:) but am very shy pa.\nham,Does not operate after  &lt;#&gt;  or what\nham,Its not the same here. Still looking for a job. How much do Ta\'s earn there.\nham,"Sorry, I\'ll call later"\nham,K. Did you call me just now ah?\nham,Ok i am on the way to home hi hi\nham,You will be in the place of that man\nham,Yup next stop.\nham,"I call you later, don\'t have network. If urgnt, sms me."\nham,For real when u getting on yo? I only need 2 more tickets and one more jacket and I\'m done. I already used all my multis.\nham,Yes I started to send requests to make it but pain came back so I\'m back in bed. Double coins at the factory too. I gotta cash in all my nitros.\nham,I\'m really not up to it still tonight babe\nham,"Ela kano.,il download, come wen ur free.."\nham,Yeah do! Don\xe2\x80\x98t stand to close tho- you\xe2\x80\x98ll catch something!\nham,Sorry to be a pain. Is it ok if we meet another night? I spent late afternoon in casualty and that means i haven\'t done any of y stuff42moro and that includes all my time sheets and that. Sorry.\nham,Smile in Pleasure Smile in Pain Smile when trouble pours like Rain Smile when sum1 Hurts U Smile becoz SOMEONE still Loves to see u Smiling!!\nspam,Please call our customer service representative on 0800 169 6031 between 10am-9pm as you have WON a guaranteed \xc2\xa31000 cash or \xc2\xa35000 prize!\nham,Havent planning to buy later. I check already lido only got 530 show in e afternoon. U finish work already?\nspam,"Your free ringtone is waiting to be collected. Simply text the password ""MIX"" to 85069 to verify. Get Usher and Britney. FML, PO Box 5249, MK17 92H. 450Ppw 16"\nham,Watching telugu movie..wat abt u?\nham,i see. When we finish we have loads of loans to pay\nham,"Hi. Wk been ok - on hols now! Yes on for a bit of a run. Forgot that i have hairdressers appointment at four so need to get home n shower beforehand. Does that cause prob for u?"""\nham,I see a cup of coffee animation\nham,Please don\'t text me anymore. I have nothing else to say.\nham,Okay name ur price as long as its legal! Wen can I pick them up? Y u ave x ams xx\nham,I\'m still looking for a car to buy. And have not gone 4the driving test yet.\nham,As per your request \'Melle Melle (Oru Minnaminunginte Nurungu Vettam)\' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune\nham,"wow. You\'re right! I didn\'t mean to do that. I guess once i gave up on boston men and changed my search location to nyc, something changed. Cuz on my signin page it still says boston."\nham,Umma my life and vava umma love you lot dear\nham,Thanks a lot for your wishes on my birthday. Thanks you for making my birthday truly memorable.\nham,"Aight, I\'ll hit you up when I get some cash"\nham,How would my ip address test that considering my computer isn\'t a minecraft server\nham,I know! Grumpy old people. My mom was like you better not be lying. Then again I am always the one to play jokes...\nham,Dont worry. I guess he\'s busy.\nham,What is the plural of the noun research?\nham,Going for dinner.msg you after.\nham,I\'m ok wif it cos i like 2 try new things. But i scared u dun like mah. Cos u said not too loud.\nspam,GENT! We are trying to contact you. Last weekends draw shows that you won a \xc2\xa31000 prize GUARANTEED. Call 09064012160. Claim Code K52. Valid 12hrs only. 150ppm\nham,"Wa, ur openin sentence very formal... Anyway, i\'m fine too, juz tt i\'m eatin too much n puttin on weight...Haha... So anythin special happened?"\nham,"As I entered my cabin my PA said, \'\' Happy B\'day Boss !!\'\'. I felt special. She askd me 4 lunch. After lunch she invited me to her apartment. We went there."\nspam,You are a winner U have been specially selected 2 receive \xc2\xa31000 or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810910p/min (18+)\nham,Goodo! Yes we must speak friday - egg-potato ratio for tortilla needed!\nham,Hmm...my uncle just informed me that he\'s paying the school directly. So pls buy food.\nspam,PRIVATE! Your 2004 Account Statement for 07742676969 shows 786 unredeemed Bonus Points. To claim call 08719180248 Identifier Code: 45239 Expires\nspam,"URGENT! Your Mobile No. was awarded \xc2\xa32000 Bonus Caller Prize on 5/9/03 This is our final try to contact U! Call from Landline 09064019788 BOX42WR29C, 150PPM"\nham,here is my new address -apples&pairs&all that malarky\nspam,Todays Voda numbers ending 7548 are selected to receive a $350 award. If you have a match please call 08712300220 quoting claim code 4041 standard rates app\nham,I am going to sao mu today. Will be done only at 12\nham,\xc3\x9c predict wat time \xc3\xbc\'ll finish buying?\nham,"Good stuff, will do."\nham,"Just so that you know,yetunde hasn\'t sent money yet. I just sent her a text not to bother sending. So its over, you dont have to involve yourself in anything. I shouldn\'t have imposed anything on you in the first place so for that, i apologise."\nham,Are you there in room.\nham,HEY GIRL. HOW R U? HOPE U R WELL ME AN DEL R BAK! AGAIN LONG TIME NO C! GIVE ME A CALL SUM TIME FROM LUCYxx\nham,K..k:)how much does it cost?\nham,I\'m home.\nham,"Dear, will call Tmorrow.pls accomodate."\nham,First answer my question.\nspam,Sunshine Quiz Wkly Q! Win a top Sony DVD player if u know which country the Algarve is in? Txt ansr to 82277. \xc2\xa31.50 SP:Tyrone\nspam,Want 2 get laid tonight? Want real Dogging locations sent direct 2 ur mob? Join the UK\'s largest Dogging Network bt Txting GRAVEL to 69888! Nt. ec2a. 31p.msg@150p\nham,I only haf msn. It\'s yijue@hotmail.com\nham,He is there. You call and meet him\nham,No no. I will check all rooms befor activities\nspam,You\'ll not rcv any more msgs from the chat svc. For FREE Hardcore services text GO to: 69988 If u get nothing u must Age Verify with yr network & try again\nham,Got c... I lazy to type... I forgot \xc3\xbc in lect... I saw a pouch but like not v nice...\nham,"K, text me when you\'re on the way"\nham,"Sir, Waiting for your mail."\nham,"A swt thought: ""Nver get tired of doing little things 4 lovable persons.."" Coz..somtimes those little things occupy d biggest part in their Hearts.. Gud ni8"\nham,I know you are. Can you pls open the back?\nham,Yes see ya not on the dot\nham,Whats the staff name who is taking class for us?\nspam,"FreeMsg Why haven\'t you replied to my text? I\'m Randy, sexy, female and live local. Luv to hear from u. Netcollex Ltd 08700621170150p per msg reply Stop to end"\nham,Ummma.will call after check in.our life will begin from qatar so pls pray very hard.\nham,K..i deleted my contact that why?\nham,Sindu got job in birla soft ..\nham,The wine is flowing and i\'m i have nevering..\nham,Yup i thk cine is better cos no need 2 go down 2 plaza mah.\nham,Ok... Ur typical reply...\nham,As per your request \'Melle Melle (Oru Minnaminunginte Nurungu Vettam)\' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune\nham,"You are everywhere dirt, on the floor, the windows, even on my shirt. And sometimes when i open my mouth, you are all that comes flowing out. I dream of my world without you, then half my chores are out too. A time of joy for me, lots of tv shows i.ll see. But i guess like all things you just must exist, like rain, hail and mist, and when my time here is done, you and i become one."\nham,Aaooooright are you at work?\nham,I\'m leaving my house now...\nham,"Hello, my love. What are you doing? Did you get to that interview today? Are you you happy? Are you being a good boy? Do you think of me?Are you missing me ?"\nspam,Customer service annoncement. You have a New Years delivery waiting for you. Please call 07046744435 now to arrange delivery\nspam,You are a winner U have been specially selected 2 receive \xc2\xa31000 cash or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810810\nham,Keep yourself safe for me because I need you and I miss you already and I envy everyone that see\'s you in real life\nham,New car and house for my parents.:)i have only new job in hand:)\nham,I\'m so in love with you. I\'m excited each day i spend with you. You make me so happy.\nspam,-PLS STOP bootydelious (32/F) is inviting you to be her friend. Reply YES-434 or NO-434 See her: www.SMS.ac/u/bootydelious STOP? Send STOP FRND to 62468\nspam,"BangBabes Ur order is on the way. U SHOULD receive a Service Msg 2 download UR content. If U do not, GoTo wap. bangb. tv on UR mobile internet/service menu"\nham,I place all ur points on e cultures module already.\nspam,URGENT! We are trying to contact you. Last weekends draw shows that you have won a \xc2\xa3900 prize GUARANTEED. Call 09061701939. Claim code S89. Valid 12hrs only\nham,"Hi frnd, which is best way to avoid missunderstding wit our beloved one\'s?"\nham,Great escape. I fancy the bridge but needs her lager. See you tomo\nham,Yes :)it completely in out of form:)clark also utter waste.\nham,"Sir, I need AXIS BANK account no and bank address."\nham,"Hmmm.. Thk sure got time to hop ard... Ya, can go 4 free abt... Muz call u to discuss liao..."\nham,What time you coming down later?\nham,"Bloody hell, cant believe you forgot my surname Mr . Ill give u a clue, its spanish and begins with m..."\nham,"Well, i\'m gonna finish my bath now. Have a good...fine night."\nham,Let me know when you\'ve got the money so carlos can make the call\nham,U still going to the mall?\nham,"Turns out my friends are staying for the whole show and won\'t be back til ~ &lt;#&gt; , so feel free to go ahead and smoke that $ &lt;#&gt;  worth"\nham,Text her. If she doesnt reply let me know so i can have her log in\nham,Hi! You just spoke to MANEESHA V. We\'d like to know if you were satisfied with the experience. Reply Toll Free with Yes or No.\nham,You lifted my hopes with the offer of money. I am in need. Especially when the end of the month approaches and it hurts my studying. Anyways have a gr8 weekend\nham,Lol no. U can trust me.\nham,ok. I am a gentleman and will treat you with dignity and respect.\nham,"He will, you guys close?"\nham,Going on nothing great.bye\nham,Hello handsome ! Are you finding that job ? Not being lazy ? Working towards getting back that net for mummy ? Where\'s my boytoy now ? Does he miss me ?\nham,"Haha awesome, be there in a minute"\nspam,Please call our customer service representative on FREEPHONE 0808 145 4742 between 9am-11pm as you have WON a guaranteed \xc2\xa31000 cash or \xc2\xa35000 prize!\nham,Have you got Xmas radio times. If not i will get it now\nham,I jus reached home. I go bathe first. But my sis using net tell u when she finishes k...\nspam,Are you unique enough? Find out from 30th August. www.areyouunique.co.uk\nham,I\'m sorry. I\'ve joined the league of people that dont keep in touch. You mean a great deal to me. You have been a friend at all times even at great personal cost. Do have a great week.|\nham,Hi :)finally i completed the course:)\nham,It will stop on itself. I however suggest she stays with someone that will be able to give ors for every stool.\nham,How are you doing? Hope you\'ve settled in for the new school year. Just wishin you a gr8 day\nham,Gud mrng dear hav a nice day\nham,Did u got that persons story\nham,is your hamster dead? Hey so tmr i meet you at 1pm orchard mrt?\nham,Hi its Kate how is your evening? I hope i can see you tomorrow for a bit but i have to bloody babyjontet! Txt back if u can. :) xxx\nham,"Found it, ENC  &lt;#&gt; , where you at?"\nham,I sent you  &lt;#&gt;  bucks\nham,Hello darlin ive finished college now so txt me when u finish if u can love Kate xxx\nham,Your account has been refilled successfully by INR  &lt;DECIMAL&gt; . Your KeralaCircle prepaid account balance is Rs  &lt;DECIMAL&gt; . Your Transaction ID is KR &lt;#&gt; .\nham,Goodmorning sleeping ga.\nham,U call me alter at 11 ok.\nham,\xc3\x9c say until like dat i dun buy ericsson oso cannot oredi lar...\nham,"As I entered my cabin my PA said, \'\' Happy B\'day Boss !!\'\'. I felt special. She askd me 4 lunch. After lunch she invited me to her apartment. We went there."\nham,"Aight yo, dats straight dogg"\nham,You please give us connection today itself before  &lt;DECIMAL&gt;  or refund the bill\nham,Both :) i shoot big loads so get ready!\nham,"What\'s up bruv, hope you had a great break. Do have a rewarding semester."\nham,Home so we 

In [32]:
df = pd.read_csv('/content/spam.csv')
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
#                        DATA CLEANING

In [33]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [34]:
df.duplicated().sum()

np.int64(415)

In [80]:
df.drop_duplicates(inplace=True)

In [ ]:
#                       STEMMING AND STOPWARDS

In [68]:
ps=PorterStemmer()
stop_words=stopwords.words('english')

In [69]:
corpus=[]
for i in range(len(df)):
  review=re.sub('[^a-zA-Z]',' ',df['Message'].iloc[i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [41]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather promis wont take help grant fulfil promis wonder bless time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt messag click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watch',
 'eh u rememb spell name ye v naughti make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur nation team eg england tri wale scotland txt poboxox w wq',
 'serious spell name',
 'go tri month ha ha joke',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch alreadi',
 'ffffffffff alright way meet sooner',
 'forc eat slice realli hungri tho suck mark get worri know sick turn pizza lol',
 'lol alway convinc',
 'catch bu fri egg make tea eat mom left dinner feel love',
 'back amp pack car let know room',
 'ahhh work vagu rememb feel like lol',
 'wait still clear sure sarcast x want live us',
 'yeah got v apologet n fallen actin like spoilt child got caught till go badli cheer',
 'k tell anyth',
 'fear faint housework quick cuppa',
 'thank subscript rington uk mobil charg month pleas confirm repli ye repli charg',
 'yup ok go home look time msg xuhui go learn nd may lesson',
 'oop let know roommat done',
 'see letter b car',
 'anyth lor u decid',
 'hello saturday go text see decid anyth tomo tri invit anyth',
 'pl go ahead watt want sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummi',
 'rodger burn msg tri call repli sm free nokia mobil free camcord pleas call deliveri tomorrow',
 'see',
 'great hope like man well endow lt gt inch',
 'call messag miss call',
 'get hep b immunis nigeria',
 'fair enough anyth go',
 'yeah hope tyler could mayb ask around bit',
 'u know stubborn even want go hospit kept tell mark weak sucker hospit weak sucker',
 'think first time saw class',
 'gram usual run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride earli tomorrow morn crash place tonight',
 'wow never realiz embarass accomod thought like sinc best could alway seem happi cave sorri give sorri offer sorri room embarass',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end repli end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrat year special cinema pass call c suprman v matrix starwar etc free bx ip pm dont miss',
 'sorri call later meet',
 'tell reach',
 'ye gauti sehwag odi seri',
 'gonna pick burger way home even move pain kill',
 'ha ha ha good joke girl situat seeker',
 'part check iq',
 'sorri roommat took forev ok come',
 'ok lar doubl check wif da hair dresser alreadi said wun cut v short said cut look nice',
 'valu custom pleas advis follow recent review mob award bonu prize call',
 'today song dedic day song u dedic send ur valuabl frnd first rpli',
 'urgent ur award complimentari trip eurodisinc trav aco entri claim txt di morefrmmob shracomorsglsuplt ls aj',
 'hear new divorc barbi come ken stuff',
 'plane give month end',
 'wah lucki man save money hee',
 'finish class',
 'hi babe im home wanna someth xx',
 'k k perform',
 'u call',
 'wait machan call free',
 'that cool gentleman treat digniti respect',
 'like peopl much shi pa',
 'oper lt gt',
 'still look job much ta earn',
 'sorri call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sm',
 'real u get yo need ticket one jacket done alreadi use multi',
 'ye start send request make pain came back back bed doubl coin factori gotta cash nitro',
 'realli still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch someth',
 'sorri pain ok meet anoth night spent late afternoon casualti mean done stuff moro includ time sheet sorri',
 'smile pleasur smile pain smile troubl pour like rain smile sum hurt u smile becoz someon still love see u smile',
 'pleas call custom servic repres pm guarante cash prize',
 'havent plan buy later check alreadi lido got show e afternoon u finish work alreadi',
 'free rington wait collect simpli text password mix verifi get usher britney fml po box mk h ppw',
 'watch telugu movi wat abt u',
 'see finish load loan pay',
 'hi wk ok hol ye bit run forgot hairdress appoint four need get home n shower beforehand caus prob u',
 'see cup coffe anim',
 'pleas text anymor noth els say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still look car buy gone drive test yet',
 'wow right mean guess gave boston men chang search locat nyc someth chang cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thank lot wish birthday thank make birthday truli memor',
 'aight hit get cash',
 'would ip address test consid comput minecraft server',
 'know grumpi old peopl mom like better lie alway one play joke',
 'dont worri guess busi',
 'plural noun research',
 'go dinner msg',
 'ok wif co like tri new thing scare u dun like mah co u said loud',
 'gent tri contact last weekend draw show prize guarante call claim code k valid hr ppm',
 'wa ur openin sentenc formal anyway fine juz tt eatin much n puttin weight haha anythin special happen',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'winner u special select receiv holiday flight inc speak live oper claim p min',
 'goodo ye must speak friday egg potato ratio tortilla need',
 'hmm uncl inform pay school directli pl buy food',
 'privat account statement show unredeem bonu point claim call identifi code expir',
 'urgent mobil award bonu caller prize final tri contact u call landlin box wr c ppm',
 'new address appl pair malarki',
 'today voda number end select receiv award match pleas call quot claim code standard rate app',
 'go sao mu today done',
 'predict wat time finish buy',
 'good stuff',
 'know yetund sent money yet sent text bother send dont involv anyth impos anyth first place apologis',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pl accomod',
 'first answer question',
 'sunshin quiz wkli q win top soni dvd player u know countri algarv txt ansr sp tyron',
 'want get laid tonight want real dog locat sent direct ur mob join uk largest dog network bt txting gravel nt ec p msg p',
 'haf msn yiju hotmail com',
 'call meet',
 'check room befor activ',
 'rcv msg chat svc free hardcor servic text go u get noth u must age verifi yr network tri',
 'got c lazi type forgot lect saw pouch like v nice',
 'k text way',
 'sir wait mail',
 'swt thought nver get tire littl thing lovabl person coz somtim littl thing occupi biggest part heart gud ni',
 'know pl open back',
 'ye see ya dot',
 'what staff name take class us',
 'freemsg repli text randi sexi femal live local luv hear u netcollex ltd p per msg repli stop end',
 'ummma call check life begin qatar pl pray hard',
 'k delet contact',
 'sindu got job birla soft',
 'wine flow never',
 'yup thk cine better co need go plaza mah',
 'ok ur typic repli',
 'everywher dirt floor window even shirt sometim open mouth come flow dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done becom one',
 'aaooooright work',
 'leav hous',
 'hello love get interview today happi good boy think miss',
 'custom servic annonc new year deliveri wait pleas call arrang deliveri',
 'winner u special select receiv cash holiday flight inc speak live oper claim',
 'keep safe need miss alreadi envi everyon see real life',
 'new car hous parent new job hand',
 'love excit day spend make happi',
 'pl stop bootydeli f invit friend repli ye see www sm ac u bootydeli stop send stop frnd',
 'bangbab ur order way u receiv servic msg download ur content u goto wap bangb tv ur mobil internet servic menu',
 'place ur point e cultur modul alreadi',
 'urgent tri contact last weekend draw show prize guarante call claim code valid hr',
 'hi frnd best way avoid missunderstd wit belov one',
 'great escap fanci bridg need lager see tomo',
 'ye complet form clark also utter wast',
 'sir need axi bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discuss liao',
 'time come later',
 'bloodi hell cant believ forgot surnam mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know got money carlo make call',
 'u still go mall',
 'turn friend stay whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt repli let know log',
 'hi spoke maneesha v like know satisfi experi repli toll free ye',
 'lift hope offer money need especi end month approach hurt studi anyway gr weekend',
 'lol u trust',
 'ok gentleman treat digniti respect',
 'guy close',
 'go noth great bye',
 'hello handsom find job lazi work toward get back net mummi boytoy miss',
 'haha awesom minut',
 'pleas call custom servic repres freephon pm guarante cash prize',
 'got xma radio time get',
 'ju reach home go bath first si use net tell u finish k',
 'uniqu enough find th august www areyouuniqu co uk',
 'sorri join leagu peopl dont keep touch mean great deal friend time even great person cost great week',
 'hi final complet cours',
 'stop howev suggest stay someon abl give or everi stool',
 'hope settl new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got person stori',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate even hope see tomorrow bit bloodi babyjontet txt back u xxx',
 'found enc lt gt',
 'sent lt gt buck',
 'hello darlin ive finish colleg txt u finish u love kate xxx',
 'account refil success inr lt decim gt keralacircl prepaid account balanc rs lt decim gt transact id kr lt gt',
 'goodmorn sleep ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'aight yo dat straight dogg',
 'pleas give us connect today lt decim gt refund bill',
 'shoot big load get readi',
 'bruv hope great break reward semest',
 'home alway chat',
 'k k good studi well',
 'yup noe leh',
 'sound great home',
 'final match head toward draw predict',
 'tire slept well past night',
 'easi ah sen got select mean good',
 'take exam march',
 'yeah think use gt atm regist sure anyway help let know sure readi',
 'ok prob take ur time',
 'os call ubandu run without instal hard disk use os copi import file system give repair shop',
 'u say leh cours noth happen lar say v romant ju bit lor thk e nite sceneri nice leh',
 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would realli appreci call need someon talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo follow ur star sign e g horo ari',
 'hey compani elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happi morn',
 'dear good morn',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear go rubber place',
 'sorri batteri die yeah',
 'ye tv alway avail work place',
 'text meet someon sexi today u find date even flirt u join p repli name age eg sam msg recd thirtyeight penc',
 'print oh lt gt come upstair',
 'ill littl closer like bu stop street',
 'wil reach',
 'new theori argument win situat lose person dont argu ur friend kick amp say alway correct',
 'u secret admir look make contact u find r reveal think ur special call',
 'tomarrow final hear laptop case cant',
 'pleassssssseeeee tel v avent done sportsx',
 'okay shine meant sign sound better',
 'although told u dat baig face watch realli like e watch u gave co fr u thanx everyth dat u done today touch',
 'u rememb old commerci',
 'late said websit dont slipper',
 'ask call ok',
 'kalli wont bat nd inning',
 'didnt work oh ok goodnight fix readi time wake dearli miss good night sleep',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovabl bcum angri wid u dnt take serious coz angri childish n true way show deep affect care n luv kettoda manda nice day da',
 '',
 'up day also ship compani take wk way usp take week get lag may bribe nipost get stuff',
 'back lemm know readi',
 'necessarili expect done get back though headin',
 'mmm yummi babe nice jolt suzi',
 'lover need',
 'tri contact repli offer video handset anytim network min unlimit text camcord repli call',
 'park next mini come today think',
 'yup',
 'anyway go shop co si done yet dun disturb u liao',
 'luton ring ur around h',
 'hey realli horni want chat see nake text hot text charg pm unsubscrib text stop',
 'dint come us',
 'wana plan trip sometm',
 'sure yet still tri get hold',
 'ur rington servic chang free credit go club mobil com choos content stop txt club stop p wk club po box mk wt',
 'evo download flash jealou',
 'rington club get uk singl chart mobil week choos top qualiti rington messag free charg',
 'come mu sort narcot situat',
 'night end anoth day morn come special way may smile like sunni ray leav worri blue blue bay',
 'hmv bonu special pound genuin hmv voucher answer easi question play send hmv info www percent real com',
 'usf guess might well take car',
 'object bf come',
 'thanx',
 'tell rob mack gf theater',
 'awesom see bit',
 'sent type food like',
 'done hand celebr full swing yet',
 'got call tool',
 'wen u miss someon person definit special u person special miss keep touch gdeve',
 'ok ask money far',
 'oki',
 'yeah think usual guy still pass last night get ahold anybodi let know throw',
 'k might come tonight class let earli',
 'ok',
 'hi babi im cruisin girl friend r u give call hour home that alright fone fone love jenni xxx',
 'life mean lot love life love peopl life world call friend call world ge',
 'dear shall mail tonit busi street shall updat tonit thing look ok varunnathu edukkukaye raksha ollu good one real sens',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam work',
 'oop got bit',
 'much buzi',
 'accident delet messag resend pleas',
 'mobil custom may claim free camera phone upgrad pay go sim card loyalti call offer end thfeb c appli',
 'unless situat go gurl would appropri',
 'hurt teas make cri end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pl send messag',
 'need coffe run tomo believ time week alreadi',
 'awesom rememb last time got somebodi high first time diesel v',
 'shit realli shock scari cant imagin second def night u think somewher could crash night save taxi',
 'oh way food fridg want go meal tonight',
 'womdarful actor',
 'sm ac blind date u rodd aberdeen unit kingdom check http img sm ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jo ask u wana meet',
 'lol ye friendship hang thread caus u buy stuff',
 'themob check newest select content game tone gossip babe sport keep mobil fit funki text wap',
 'garag key bookshelf',
 'today accept day u accept brother sister lover dear best clo lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rpli mean enemi',
 'think ur smart win week weekli quiz text play cs winnersclub po box uz gbp week',
 'say give call friend got money definit buy end week',
 'hi way u day normal way real ur uniqu hope know u rest mylif hope u find wot lost',
 'made day great day',
 'k k advanc happi pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'realli dude friend afraid',
 'decemb mobil mth entitl updat latest colour camera mobil free call mobil updat co free',
 'coffe cake guess',
 'merri christma babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l co buse hav gon past co full im still waitin pete x',
 'would great guild could meet bristol road somewher get touch weekend plan take flight good week',
 'problem',
 'hi da today class',
 'say good sign well know track record read women',
 'cool text park',
 'read text sent meant joke read light',
 'k k apo k good movi',
 'mayb could get book tomo return immedi someth',
 'call germani penc per minut call fix line via access number prepay direct access',
 'chanc might evapor soon violat privaci steal phone number employ paperwork cool pleas contact report supervisor',
 'valentin day special win quiz take partner trip lifetim send go p msg rcvd custcar',
 'ta daaaaa home babe still',
 'cool come havent wine dine',
 'sleep surf',
 'u call right call hand phone',
 'ok great thanx lot',
 'take post come must text happi read one wiv hello carolin end favourit bless',
 'u hide stranger',
 'interest like',
 'sister clear two round birla soft yesterday',
 'gudnit tc practic go',
 'di yiju ju saw ur mail case huim havent sent u num di num',
 'one small prestig problem',
 'fanci shag interest sextextuk com txt xxuk suzi txt cost per msg tnc websit x',
 'check realli miss see jeremiah great month',
 'nah help never iphon',
 'car hour half go apeshit',
 'today sorri day ever angri ever misbehav hurt plz plz slap urself bcoz ur fault basic good',
 'yo guy ever figur much need alcohol jay tri figur much safe spend weed',
 'lt gt ish minut minut ago wtf',
 'thank call forgot say happi onam sirji fine rememb met insur person meet qatar insha allah rakhesh ex tata aig join tissco tayseer',
 'ur cash balanc current pound maxim ur cash send cash p msg cc hg suit land row w j hl',
 'actor work work even sleep late sinc unemploy moment alway sleep late unemploy everi day saturday',
 'hello got st andrew boy long way cold keep post',
 'ha ha cool cool chikku chikku db',
 'oh ok prob',
 'check audrey statu right',
 'busi tri finish new year look forward final meet',
 'good afternoon sunshin dawn day refresh happi aliv breath air smile think love alway',
 'well know z take care worri',
 'updat xma offer latest motorola sonyericsson nokia free bluetooth doubl min txt orang call mobileupd call optout f q',
 'discount code rp stop messag repli stop www regalportfolio co uk custom servic',
 'wat uniform get',
 'cool text readi',
 'hello boytoy geeee miss alreadi woke wish bed cuddl love',
 'spoil bed well',
 'go bath msg next lt gt min',
 'cant keep talk peopl sure pay agre price pl tell want realli buy much will pay',
 'thank rington order refer charg gbp per week unsubscrib anytim call custom servic',
 'say happen',
 'could seen recognis face',
 'well lot thing happen lindsay new year sigh bar ptbo blue heron someth go',
 'keep payasam rinu bring',
 'taught ranjith sir call sm like becau he verifi project prabu told today pa dont mistak',
 'guess worri must know way bodi repair quit sure worri take slow first test guid ovul relax noth said reason worri keep followin',
 'yeah sure give coupl minut track wallet',
 'hey leav big deal take care',
 'hey late ah meet',
 'doubl min txt month free bluetooth orang avail soni nokia motorola phone call mobileupd call optout n dx',
 'took mr owl lick',
 'custom place call',
 'mm time dont like fun',

In [ ]:
#                      COUNT-VERCORIZATION

In [43]:
cv=CountVectorizer(max_features=500,binary=True)

In [ ]:
#                    FEATURE SCALING

In [44]:
x=cv.fit_transform(corpus).toarray()

In [45]:
x.shape

(5157, 500)

In [46]:
x[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#                            ENCODING THE Y AXIS

In [47]:
label=LabelEncoder()

In [48]:
y=label.fit_transform(df['Category'])

In [49]:
print(label.classes_)
print(y[:10])

['ham' 'spam']
[0 0 1 0 0 1 0 0 1 1]

In [ ]:
#                         DATA SPLITTING

In [81]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
#                   HYPER PARAMETER TUNING

In [51]:
weak_learner=DecisionTreeClassifier(max_depth=1)

In [ ]:
#                        MODEL SELECTION

In [52]:
model=AdaBoostClassifier(estimator=weak_learner,n_estimators=100,learning_rate=1,random_state=42)

In [82]:
model.fit(x_train,y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),
                   learning_rate=1, n_estimators=100, random_state=42)

In [83]:
y_pred = model.predict(X_test)
accuracy_score(y_test, y_pred)

0.9011627906976745

In [84]:
y_pred = model.predict(X_train)
accuracy_score(y_train, y_pred)

0.9241212121212121

In [ ]:
#              PREDICTIVE PART

In [70]:
ps=PorterStemmer()

In [86]:
def preprocess(message):
  review=re.sub('[^a-zA-Z]',' ',message)
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  return review


def predict_message(message):
  cleaned_message = preprocess(message)
  vectorized_message = cv.transform([cleaned_message]).toarray()
  pred=model.predict(vectorized_message)
  return label.inverse_transform([pred][0])

In [87]:
df.iloc[1000,0][:200] # FROM 1000 ROW AND ZEROTH COLUMN. : means starting from 200 word lenght

'ham'

In [88]:
print(predict_message('In our household, we are enormous fans of A Christmas Carol and watch virtually every version each Christmas, including the old 1938 Reginald Owen and the modern 1999 Patrick Stewart. Our overall favorite is the 1951 black & white classic, because Alastair Sim IS Ebeneezer Scrooge and his conversion'))

['ham']